// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkImHd39IMfQNdytRVxFY3yhzQwcEwvrQ',
    appId: '1:159382536980:web:ec2dcfab18de1498333801',
    messagingSenderId: '159382536980',
    projectId: 'mytherapypal',
    authDomain: 'mytherapypal.firebaseapp.com',
    databaseURL: 'https://mytherapypal-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mytherapypal.appspot.com',
    measurementId: 'G-BRSDP2FNM2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqtGFY94S4kHd0rfuhPSzxjkPhfjKHcjw',
    appId: '1:159382536980:android:48e66458ba74bfb0333801',
    messagingSenderId: '159382536980',
    projectId: 'mytherapypal',
    databaseURL: 'https://mytherapypal-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mytherapypal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYGvhhUZWwWaDFZz8Aw03kAJxPLojDmN4',
    appId: '1:159382536980:ios:fda062a6a35c217a333801',
    messagingSenderId: '159382536980',
    projectId: 'mytherapypal',
    databaseURL: 'https://mytherapypal-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mytherapypal.appspot.com',
    iosBundleId: 'com.myTherapyPal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYGvhhUZWwWaDFZz8Aw03kAJxPLojDmN4',
    appId: '1:159382536980:ios:bed67e6e406d2f1f333801',
    messagingSenderId: '159382536980',
    projectId: 'mytherapypal',
    databaseURL: 'https://mytherapypal-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mytherapypal.appspot.com',
    iosBundleId: 'com.myTherapyPal.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXlQ9lhzngAHiyW9tSwMmoJX9M6xigzBI',
    appId: '1:159382536980:web:02ca925c12a241af333801',
    messagingSenderId: '159382536980',
    projectId: 'mytherapypal',
    authDomain: 'mytherapypal.firebaseapp.com',
    databaseURL: 'https://mytherapypal-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mytherapypal.appspot.com',
    measurementId: 'G-R15BC5R56C',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBXlQ9lhzngAHiyW9tSwMmoJX9M6xigzBI',
    appId: '1:159382536980:web:2f745be2c2f17c3d333801',
    messagingSenderId: '159382536980',
    projectId: 'mytherapypal',
    authDomain: 'mytherapypal.firebaseapp.com',
    databaseURL: 'https://mytherapypal-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mytherapypal.appspot.com',
    measurementId: 'G-7SLG4ERVL2',
  );
}
